services:
  client:
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
    
  server:
    build: ./backend/
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s