import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import ContainerLayout from "@/components/Shared/ContainerLayout";
import QueryProvider from "@/components/Providers/QueryProvider";
import { UserProvider } from "@/components/Providers/UserProvider";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OU Insight Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <QueryProvider>
          <UserProvider>
            <ThemeProvider>
              <ContainerLayout>
                {children}
              </ContainerLayout>
            </ThemeProvider>
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
};