import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Custombar/AppSidebar";
import Navbar from "@/components/Custombar/Navbar";
import Bottombar from "@/components/Custombar/Bottombar";
import QueryProvider from "@/components/Providers/QueryProvider";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OU Insight Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <QueryProvider>
          <ThemeProvider>
            <div className="flex w-full min-h-screen flex-col">
              <div className="relative flex h-full w-full flex-1 transition-colors z-0">
                <SidebarProvider>
                  <AppSidebar />
                  <div className="relative flex h-full max-w-full flex-1 flex-col">
                    <div className="relative flex-1 flex flex-col transition-[width,height] ease-linear">
                      <Navbar />
                      <main className="flex w-full h-full p-6 bg-background">
                        {children}
                      </main>
                      <Bottombar />
                    </div>
                  </div>
                </SidebarProvider>
              </div>
            </div>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
};