import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar/AppSidebar";
import Navbar from "@/components/Custombar/Navbar";
import Bottombar from "@/components/Custombar/Bottombar";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "OU Insight Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex w-full flex-col h-screen">
            <SidebarTrigger />
            <Navbar />
            {children}
            <Bottombar />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
